(defun test ()
  (let ((*print-circle* t))
    (declare (special *print-circle*))
    (print '#1=(#1#))
    (print '#1=(a . #1#))
    (print '(a b #1=(c d (e . #1#))))
    (print '#1=#(#1#))
    (print '(a b (c d) #1=(c d) #1#))
    (values)))
