# .cirrus.yml -- Cirrus CI configuration for the MPS

# FIXME: Just a test based on https://cirrus-ci.org/guide/macOS/

XCA6LL_task:
  macos_instance:
    # What does this syntax mean?
    image: ghcr.io/cirruslabs/macos-ventura-xcode
  script:
    - uname -a
    - cc --version
    - cc -dumpmachine
    - ./configure --prefix=$PWD/prefix && make install && make test

# https://cirrus-ci.org/guide/writing-tasks/ doesn't seem to allow for FreeBSD on arm64

FRI6LL_task:
  freebsd_instance:
    # Why is this a "family"?
    image_family: freebsd-13-1
  # Which compiler will this end up with by default?  Clang.
  script:
    - uname -a
    - pkg install -y gmake
    - cc --version
    - cc -dumpmachine
    - ./configure --prefix=$PWD/prefix-clang && make install && make test

FRI6GC_task:
  freebsd_instance:
    # Why is this a "family"?
    image_family: freebsd-13-1
  script:
    - uname -a
    - pkg install -y gmake gcc
    - gcc --version
    - gcc -dumpmachine
    - CC=gcc ./configure --prefix=$PWD/prefix-gcc && make install && make test

# Is this really "LI" if it's a docker container?  Does it matter?
LIA6GC_task:
  arm_container:
    image: gcc # https://hub.docker.com/_/gcc
  script:
    - uname -a
    - cc --version
    - cc -dumpmachine
    - ./configure --prefix=$PWD/prefix && make install && make test

LIA6LL_task:
  arm_container:
    image: ubuntu # https://hub.docker.com/_/ubuntu
  script:
    - uname -a
    - apt-get install -y clang
    - clang --version
    - clang -dumpmachine
    - CC=clang ./configure --prefix=$PWD/prefix && make install && make test
