#!/bin/sh
# tool/check-copyright-dates -- check copyrights dates are consistent with Git dates
# Richard Brooksby, Ravenbrook Limited, 2023-03-23
#
# Copyright (c) 2023 Ravenbrook Limited.  See end of file for license.
#
# FIXME: Only works for Ravenbrook copyrights.  Should perhaps look
# for the last notice in a group of lines.
#
# FIXME: Will break if a filename has a '!' in it, because that isn't
# escaped to the sed expression.

{
    git ls-tree -r --name-only HEAD |
    while read -r filename; do
	# Skip binary files
	if ! file --brief -- "$filename" | grep -q 'text'; then continue; fi
	
	# Debugging output
	# echo 1>&2 "$filename: checking..."

	# Ask Git for the year of the last commit to the file
	author_year=$(git log -1 --format="%ai" "$filename" |
			  sed --silent --regexp-extended \
			      --expression='s/^([[:digit:]]{4})-.*$/\1/p')

	# Search for copyright notices and extract the end years
	nl < "$filename" |
	    sed --silent --regexp-extended \
		--expression='s!^[[:space:]]*([[:digit:]]+)[[:space:]].*Copyright[[:space:]]+(.*[[:space:]]+)?([[:digit:]]{4}[[:space:]]*-[[:space:]]*)?([[:digit:]]{4})[[:space:]]+Ravenbrook[[:space:]].*$!'"$filename"':\1 '"$author_year"' \4!p'
    done
} | {
    code=0
    while read -r fileline author_year end_year; do
	# echo 1>&2 "$fileline: Checking $author_year = $end_year"
	if test "$end_year" -ne "$author_year"; then
	    code=1
	    echo 1>&2 "$fileline: Copyright end year $end_year does not match Git author year $author_year"
	fi
    done
    exit $code
}

# A. REFERENCES
#
# [None]
#
#
# B. DOCUMENT HISTORY
#
# 2023-03-23 RB Created in response to review brainstorm <https://github.com/Ravenbrook/mps/pull/179#issuecomment-1481486144>.
#
#
# C. COPYRIGHT AND LICENSE
#
# Copyright (C) 2023 Ravenbrook Limited <https://www.ravenbrook.com/>.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# $Id$
