#!/bin/bash
# Estimate the risk of changes to the MPS.
#
# [Insert why this was developed, ref to issue, etc.  RB 2023-02-24]
#
# Takes arguments to ``git log``.  For example, to assess changes on
# master::
#
#   tool/git-risks --first-parent -n 10 master
#
# The estimate of the risks of changing files is stored in
# tool/git-riskiness
#
# TODO: Take option to select risk column argument to sort.
#
# Developed from <https://info.ravenbrook.com/mail/2023/02/21/17-08-50/0/>.

git log --format="%H %h %s" "$@" |
while read -r hash commit subject; do
    risks=$(
	# Strip comments and blank lines from git-riskiness
	sed --regexp-extended \
	    --expression='s/[[:space:]]*#.*$//; /^[[:space:]]*$/ d' < tool/git-riskiness |
	# Filter lines that mention files changed in the commit
	(
	    grep --fixed-strings \
		 --file=<(git log --max-count=1 --patch \
			     --diff-merges=on --name-only \
			     --pretty="format:" "$hash") ||
		echo "0 0 no-match"
	) |
	# Pick the riskiest
        sort --numeric --reverse --key=1 |
	head --lines=1
    )
    echo "$commit $risks $subject"
done
